domain_path: D:\Graduation_Project\NN_project\Vitis\NN_Platform\export\NN_Platform\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
