domain_path: D:\Graduation_Project\NIDS_ARTYZ7\Vitis\NIDS_platform\export\NIDS_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
